language: php

php:
  - 5.6
  - 7.0
  - nightly

sudo: false

env:
  global:
    - PATH="$HOME/.composer/vendor/bin:$PATH"
    - "FTP_USER=QlyYGjaIwQGEwodVLgiiXcOBm8qWlMliI2B1SjqbU6matj0FVkXblIELFyY58Fz6zqzwoVye29Q+2znZVaFltqykUWDnaWs6EUU+Kk0KumE6+Km5/OzxqQs9M9Gqyc0mAa1Kjv2NpGjPbIQvimMYkd38/3T41IlIzoINKTryoiI3XcgVfcs64uiKcgI5YQjVsxUY5ePsO4Sj3hStzxIq5XUS46qnKEINKNATwFKGLrtTnRYQquOzP5cNZdwXMVODtYz5kTb8yFw8qiXC+Vw2Rd2HIBr/n2OJCLC3yXQEBmQzhd7HTXdamT626NUwtyJ1T6PEQwf1PvwceI4SeDEP365Jrg9ZDRjEVMe4ES0v831B3CV1iI4TH6hoMD6mV66++xpMi6HrJkOXHWt92gykGaqnyYhLQYxMx2NLJHKHt9980hYrlzY1snQkb0UiuRZyuBR3Y11WHvn1ZeMRzyiFrzYWXnDH0nXYSzuSRpdR3nmQdzm3q27PlL5t5WD31SMXiRfbr7SN/SL7kyfgOl6OrPal5mA0gEuVw/UbIBqm05fEXERtpZEYclC06xlGbCtyl+dfWHQWyl7hTzgn2nXYrCWiRzFu3R092dbADFt4xLiQl66y4Q283P1rC46uNggVK3qLiqxbcsP7WqY7CIGyqEFa8XHr15BfxELFzqFigMA="
    - "FTP_PASSWORD=ZSvq9/dWJ6VOYXdldskO0hx0WXhq8Vxsp6RaCdzaDu0J+SSUAvInmWS1z9u/SBsGlr95aVoGnpQ5el0Qbzr5COjUl1Q4Ji1ViK93Zv8WDG/wV/VSM0GN2fOOdkI7OqpMQE4hG/09xX6p1Y0iS9zFAZozIr6CVYOgo7b6u5UWRisB36svlDuBZYlAcOQ8EdHVQbJ1c7DFERKPBRoPQhM/r/plu+WSz/DXhmB8YPRkzEXjLH8aCFLpokndlwh6JOTo/sMUnN0hpHBbSHnpT0BBfkygf61w6sL1LQSrO2MrrquKO92VIP/z3jPEn1buQOBWAgQ7Uq5yEmpJlPT+ZfXu5Eq7EMw82rdKY1JJIRBTUXQ765AOh2STRGattSThnvomwFXqbkirrpmi+d+NyTbVZjs7YfKyPv9a0xhG3t+vM0ncmmHi/RTBO0vQ7PC2AHzsS0W0AWl6ySJg9Vnq//9ZB+z1MdGdUQi6GJVBylp0e0QSZD63pugdXY0hqXjd7xP2xssD/m4f07Pysy0ucdMXHadtcXyx45eVG0/PPbQq5Oki5d6Lmn+oHI5ectCvQqkrpCJnSeQ1ll4hDDAjnwyA1AKgpcqx9x8YEmURsVdzBWusfpubTVvfBYsbyD/ADwmGsRpOiRM97GB1CSljnl7zNqTyer4+Lm6cPzUo3gVCMrg="

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  fast_finish: true
  include:
    - php: 5.6
      env: COMPOSER_FLAGS="--prefer-lowest"
  allow_failures:
    - php: nightly

before_install:
  - phpenv config-rm xdebug.ini

install:
  - mkdir -p ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d && echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - mkdir -p build/logs
  - composer global require satooshi/php-coveralls:@stable --no-update
  - composer global update --prefer-dist --no-interaction
  - composer update --prefer-dist --no-interaction $COMPOSER_FLAGS

before_script:
  - php generate_fake.php nexycrypt.nctu.me 0
  - php generate_fake.php nexycrypt.nctu.me 1
  - php generate_fake.php nexycrypt.nctu.me 2
  - php generate_fake.php nexycrypt.nctu.me 3
  - echo "zend_extension=xdebug.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

script:
  - vendor/bin/phpunit

after_script:
  - coveralls -v
